Implement filtering of [non-]canceled trains
endor-force/pytrafikverket pull request #21
Opened 2022-11-26 18:43 UTC by farbro

- Add arguments `--train-canceled` and `--train-not-canceled` to CLI app.
- Implement `canceled` argument for filtering in `async_get_train_stop(...)` and `async_get_next_train_stop(...)`

This could possible be implemented for ferries as well, but they do not have a "Canceled" property. Instead they have something called "Deleted", but it is unclear what it does.

2022-11-26 18:48 UTC, gjohansson-ST commented
I would suggest you only add `--train-canceled` with `true` as default and thereby you already have the option to set false to skip cancelled trains.

Should not be mixed with `deleted` which is something else

2022-11-26 19:38 UTC, farbro commented
> I would suggest you only add `--train-canceled` with `true` as default and thereby you already have the option to set false to skip cancelled trains.
But wouldn't that break backwards compatibility? How would you then request both canceled and non-canceled, as it is originally?

2022-11-26 20:23 UTC, gjohansson-ST commented
I would see it like this with `--train-canceled`
- True: Skip the filter and return full result (also default behavior)
- False: Add the filter and return only results where canceled = False

Probably we should reverse this and call it `--exclude-canceled` or something

2022-11-26 22:13 UTC, farbro commented
Ah I get it, see my new commit. We do lose the ability to filter by canceled trains, but that is a feature that will probably never be used anyway.

2022-11-27 10:12 UTC, gjohansson-ST requested changes
Some small changes

2022-11-27 10:12 UTC, gjohansson-ST commented on pytrafikverket/__main__.py
> +        parser.add_argument("--exclude-canceled-trains", action=argparse.BooleanOptionalAction, default=False)
```suggestion
        parser.add_argument("-exclude-canceled-trains", action=argparse.BooleanOptionalAction, default=False)
```

2022-11-27 10:12 UTC, gjohansson-ST commented on pytrafikverket/trafikverket_train.py
> +        exclude_canceled: typing.Optional[bool] = False,
```suggestion
        exclude_canceled: bool = False,
```
Not optional

2022-11-27 10:12 UTC, gjohansson-ST commented on pytrafikverket/trafikverket_train.py
> +        exclude_canceled: typing.Optional[bool] = False,
as above

2022-11-27 11:41 UTC, farbro commented
Thanks for your review. I applied your suggested changes and also bumped up the version.

2022-11-27 16:49 UTC, gjohansson-ST commented
Did you test it?

2022-11-27 18:27 UTC, farbro commented
I thought so. Now I tested it again, by finding a canceled departure, querying it with `-date-time` and toggling it with `-exclude-canceled-trains`.

```sh
$ python3 pytrafikverket.py -key <my-key>  -method get-next-train-stop -from-station "Stockholm C" -to-station "Norrköping C" -date-time "2022-11-27T21:38:00"                   
from_station_signature: Cst
to_station_signature:   Nr
advertised_time_at_location = 2022-11-27 21:38:00+01:00
canceled = True
deviations = ['Inställt']
estimated_time_at_location = None
id = 1500adde-115d-43e5-08da-c443c281f393
modified_time = 2022-11-27 15:32:03.108000
other_information = ['Movingo gäller.']
product_description = ['Mälartåg']
time_at_location = None
```
```sh
$ python3 pytrafikverket.py -key <my-key>  -method get-next-train-stop -from-station "Stockholm C" -to-station "Norrköping C" -date-time "2022-11-27T21:38:00" -exclude-canceled-trains
from_station_signature: Cst
to_station_signature:   Nr
advertised_time_at_location = 2022-11-27 21:54:00+01:00
canceled = False
deviations = []
estimated_time_at_location = None
id = 1500adde-115d-43e5-08da-c443d1e13afd
modified_time = 2022-11-13 06:24:58.810000
other_information = ['Movingo gäller ej.']
product_description = ['SJ InterCity']
time_at_location = None
```

-get-train-stop` behaves similarly but throws an exception for the canceled departure.

2022-11-27 19:46 UTC, gjohansson-ST commented
I guess it would make sense to get an exception when filtering out canceled but you hit a canceled on the result.
What is the exception you get?

2022-11-27 19:57 UTC, farbro commented
> What is the exception you get?
```sh
ValueError: No TrainAnnouncement found
```
thrown by `get_train_stop(...)` itself: https://github.com/farbro/pytrafikverket/blob/master/pytrafikverket/trafikverket_train.py#L262

2022-11-27 20:36 UTC, gjohansson-ST approved these changes

2022-12-04 17:19 UTC, merged